// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY3xxrNGoGWToBtyBTu_mXUBaTvCuj2z0',
    appId: '1:136276048357:web:25fe8adc7163567a75970c',
    messagingSenderId: '136276048357',
    projectId: 'fir-notification-a7a54',
    authDomain: 'fir-notification-a7a54.firebaseapp.com',
    storageBucket: 'fir-notification-a7a54.appspot.com',
    measurementId: 'G-B1FKWKWZ56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnNGHl-vrFHWKvXSUjTDtzLuTqsfV3Gn4',
    appId: '1:136276048357:android:a5eeff7c4a978be075970c',
    messagingSenderId: '136276048357',
    projectId: 'fir-notification-a7a54',
    storageBucket: 'fir-notification-a7a54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsmPHdDgeaQUuKCxT6kwBsDHzyo7MY-1c',
    appId: '1:136276048357:ios:c445e7acc3748e4675970c',
    messagingSenderId: '136276048357',
    projectId: 'fir-notification-a7a54',
    storageBucket: 'fir-notification-a7a54.appspot.com',
    iosBundleId: 'com.example.firebaseNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsmPHdDgeaQUuKCxT6kwBsDHzyo7MY-1c',
    appId: '1:136276048357:ios:264715306cc4706175970c',
    messagingSenderId: '136276048357',
    projectId: 'fir-notification-a7a54',
    storageBucket: 'fir-notification-a7a54.appspot.com',
    iosBundleId: 'com.example.firebaseNotifications.RunnerTests',
  );
}
